/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class __OrdInt8Pixel : __NumInt8Pixel {
  private HandleRef swigCPtr;

  internal __OrdInt8Pixel(IntPtr cPtr, bool cMemoryOwn) : base(VisionLabPINVOKE.__OrdInt8Pixel_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(__OrdInt8Pixel obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~__OrdInt8Pixel() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VisionLabPINVOKE.delete___OrdInt8Pixel(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public __OrdInt8Pixel() : this(VisionLabPINVOKE.new___OrdInt8Pixel__SWIG_0(), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public __OrdInt8Pixel(int height, int width) : this(VisionLabPINVOKE.new___OrdInt8Pixel__SWIG_1(height, width), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public __OrdInt8Pixel(HeightWidth hw) : this(VisionLabPINVOKE.new___OrdInt8Pixel__SWIG_2(HeightWidth.getCPtr(hw)), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public __OrdInt8Pixel(__OrdInt8Pixel image) : this(VisionLabPINVOKE.new___OrdInt8Pixel__SWIG_3(__OrdInt8Pixel.getCPtr(image)), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public __OrdInt8Pixel(__NumInt8Pixel image) : this(VisionLabPINVOKE.new___OrdInt8Pixel__SWIG_4(__NumInt8Pixel.getCPtr(image)), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void Resize(HeightWidth hw) {
    VisionLabPINVOKE.__OrdInt8Pixel_Resize__SWIG_0(swigCPtr, HeightWidth.getCPtr(hw));
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void Resize(HeightWidth hw, __OrdInt8Pixel properties) {
    VisionLabPINVOKE.__OrdInt8Pixel_Resize__SWIG_1(swigCPtr, HeightWidth.getCPtr(hw), __OrdInt8Pixel.getCPtr(properties));
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public static char BackGround() {
    char ret = VisionLabPINVOKE.__OrdInt8Pixel_BackGround();
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static char Object() {
    char ret = VisionLabPINVOKE.__OrdInt8Pixel_Object();
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
